SHOP-1: Create basic shop project
Wraan/shop-app-project pull request #1
Opened 2018-04-11 13:13 UTC by Wraan

2018-04-14 12:54 UTC, Swistak06 approved these changes
Everything is ok.

2018-04-18 19:36 UTC, polskikiel requested changes
please do only the things which are necessary in PR, otherwise code getting dirty

2018-04-18 19:36 UTC, polskikiel commented on src/main/java/com/shop/controller/HomeController.java
> +
unnecessary space

2018-04-18 19:36 UTC, polskikiel commented on src/main/java/com/shop/model/User.java
> +    @Column(name = "user_id", unique = true, nullable = false)
unnecessary unique and nullable properties if it's already @GenerateValue

2018-04-18 19:36 UTC, polskikiel commented on src/main/java/com/shop/model/User.java
> +
delete space

2018-04-18 19:36 UTC, polskikiel commented on target/classes/application.properties
> +server.port=8081
shouldn't we have target/ dir in gitignore?

2018-04-18 19:36 UTC, polskikiel commented on target/classes/application.properties
> +spring.jpa.hibernate.ddl-auto=update
I think that create-drop strategy would be better for developing

2018-04-18 19:36 UTC, polskikiel commented on src/main/resources/application.properties
> +spring.servlet.multipart.max-file-size=10MB
do we need these multipart properties in that PR?

2018-04-18 19:36 UTC, polskikiel commented on src/main/java/com/shop/model/User.java
> +    @NotBlank
Not needed in that PR

2018-04-18 19:36 UTC, polskikiel commented on shop.iml
> +<?xml version="1.0" encoding="UTF-8"?>
do we need that file? ;p

2018-04-20 10:08 UTC, closed without merging