SHOP-4: SignUp view, login and registration options
Wraan/shop-app-project pull request #7
Opened 2018-05-11 19:18 UTC by Wraan

Added SignUp view, added login option as popup(works only in index.html for now, will change other views when everything from navigation and common stuff will be ready), added registration and login options, added few fields in User model for registration form.

2018-05-12 20:18 UTC, polskikiel requested changes

2018-05-12 20:18 UTC, polskikiel commented on src/main/resources/static/js/signup-validate.js
> +    if(password === confirmPassword){
IMO cleaner solution is to check error path first:
```
if(password !== confirmPassword){
   alert("Passwords don't match");
   return false;         
}
return true;
```

2018-05-12 20:18 UTC, polskikiel commented on src/main/java/com/shop/model/User.java
> +    @NotBlank
You made all fields required. I think we only need to know mail and password. User can provide rest of the data later during shipping chose. Registration form is too long IMO.
Also u can extract dto layer to separated file and make dto to domain converter in user serivce.
Another thing is that you could provide better validation. Now i can register with email: dupaxd, that's not good.

2018-05-13 07:19 UTC, Wraan commented on src/main/java/com/shop/model/User.java
> +    @NotBlank
That's good point, I will change them later to not be required, but still they will be there just with the red * to point that, they are required/not required.

I will try to separate them.

As you can see there is NO validation done there yes, just checking if the passwords are the same.
Of cource i will do validation later on both client and server side.

2018-05-15 18:24 UTC, polskikiel approved these changes

2018-05-15 18:24 UTC, merged